### ISSUE TITLE
set up containerd to run slight

### ISSUE THREAD

**Issue by danbugs** [deislabs/spiderlightning#97]

**Comment by KaiWalter** [comment]
@danbugs what exactly would you like to achieve with this issue? Is it just containerizing one `slight` workload like in <https://github.com/KaiWalter/spiderlightning/blob/hosting-service-fabric/cluster/cluster-test/Dockerfile)>?

**Comment by danbugs** [comment]
Hey, @KaiWalter ~ Thank you for your question. I definitely should gone back and included descriptions to issues like this once we open sourced. 

That said, this issue will most likely be a contribution to:
- this (https://github.com/Mossaka/containerd-wasm-shims), and, maybe,
- this (https://github.com/deislabs/runwasi).

Are you familiar with [Fermyon's Spin](https://github.com/fermyon/spin)? If you check the containerd-wasm-shims repo, you'll see we've got a shim for it that helps serve a containerized Spin app. We hope to do something similar for Slight. I hope this clarifies the scope of the issue — let me know if it doesn't!

**Comment by KaiWalter** [comment]
Hi @danbugs, I see. That was actually, what I was talking about with @squillace 2 weeks ago: "get WASM/WASI workloads running in cluster or other environments without using OCI containers". For the moment I have to admit, that the repos you listed above are technically somewhat out of my league. So don't wait for me, please.
Anyway as I want to use my vacation time for  building up some Rust muscle I will definitely munch into those.

**Comment by KaiWalter** [comment]
After I figured out how [runwasi](https://github.com/deislabs/runwasi) is working, I can imagine to get `slight` and a module WebAssembly packaged up with a **containerd-shim** approach. But still using `docker buildx` to build the image.

**Comment by squillace** [comment]
Hi @KaiWalter was out for a few days to repower. I have only _partially_ repowered. :-| But YES, the objective will be to have a containerd-based integration into k8s. There are several reasons. 
1. customers who need a scale-out, non-proprietary control plane have by and large standardized on k8s. As a result, to reach both hyperscale and periphery compute environments k8s will be the primary early control plane that all can use in either proprietary services or connected oss.
2. You should expect that early services, then, use the k8s host. But as understanding increases, other "schedulers" will be not only welcomed but sought out. Fermyon is touting Hashicorp's Nomad; in Azure, you can imagine several other orchestrators or schedulers; in oss, we know of several customers researching running real time oses that schedule wasm functions because they do not have container infra.
3. containerd _seems_ like it's for k8s but it really isn't: it's a generic process-starting system that can be integrated easily elsewhere. As example one, docker supports `docker run --runtime=io.containerd.wasmtime.v1` now and more direct work will arrive.

**Comment by squillace** [comment]
Nonetheless, I also expect that standalone hosts like slight or spin or wasmcloud (which is its own orchestrator I note) will be popular in all areas in which k3s makes no sense as a control plane. As they should be.

**Comment by squillace** [comment]
Wait, @KaiWalter, you're on vacation but you want "tactical"? :-P 

For work with slight, just post issues! everyone can see and learn, which is an advantage. For more focused issues, mail me at ralph.squillace@ <my corp> .com and we'll set something up to make the vacation fun.

**Comment by KaiWalter** [comment]
@squillace I need this to unwind - <https://twitter.com/ancientitguy/status/1560892996991782913> - with all those heavy duty enterprise projects I usually do, where technological challenges are easily trivialized by the complexities on organization, process or social level.

**Comment by danbugs** [comment]
~check out slight (previously, `wasi-cloud`) running on a PinePhone:
![](https://user-images.githubusercontent.com/39843321/186491542-9ec876ee-13c7-4638-b938-07aee3e08b31.gif)
> video link: https://user-images.githubusercontent.com/39843321/186492047-68cf490b-1629-4113-a6dc-bb8f01bc8304.mp4


P.S. might have to click on it to zoom in or view video

**Comment by Mossaka** [comment]
Closed this issue as we move containerd related issues to https://github.com/deislabs/containerd-wasm-shims
